import Head from 'next/head'
import { Typography } from '@mui/material'
import Button from '@mui/material/Button';
import { Auth, ThemeSupa } from '@supabase/auth-ui-react'
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react'

import Search from '@/components/Search'
import styles from '@/styles/Home.module.css'


export default function Home() {
  const session = useSession()
  const supabase = useSupabaseClient()

  async function signout() {
    const { error } = await supabase.auth.signOut()
  }

  return (
    <>
      <Head>
        <title>Palmemordschatten</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="container" style={{ padding: '50px 0 100px 0' }}>
          {!session ? (
            <div>
              <Typography variant="h4" className={styles.pageHeader}>Autentisera dig</Typography>
              <Auth supabaseClient={supabase} providers={["google"]} appearance={{ theme: ThemeSupa }} theme="dark" onlyThirdPartyProviders={true} />
            </div>
          ) : (
            <div>
              <Typography variant="h4" className={styles.pageHeader}>Ställ frågor om Palmeutredningen</Typography>
              <Search session={session} />
              <Button variant="outlined" onClick={signout}> {"Logga ut"} </Button>
            </div>
          )}
        </div>
      </main>
    </>
  )
}
